### ISSUE TITLE
sysfunc.cpp compile error

### ISSUE THREAD

**Issue by DarkAngelZT** [Narazaka/yaya-shiori#1]
in line 4440:
in function CValue  CSystemFunction::RE_SPLIT_CORE:
result.format
compile error.

I've change it back to boost library function as a temporary solution. But further fix is needed

**Comment by Narazaka** [comment]
Thank you for your bug report.
But sorry, this repository is old version fork of [yaya-shiori](https://github.com/ponapalt/yaya-shiori) that was in google code at that time.
Please contribute to yaya-shiori mainline.

**Comment by DarkAngelZT** [comment]
Thank you for reply. 
I've found that mainline yesterday and already submitted my work.
